version: "3.5"

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "7000:15672"
    volumes:
      - $PWD/storage/rabbitmq1:/var/lib/rabbitmq
    environment:
      - RABBITMQ_ERLANG_COOKIE=admin
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
      - CLUSTERED=true

  haproxy:
    image: haproxy:1.6
    ports:
      - 5672:5672
      - 20000:20000
    links:
      - rabbitmq:rabbitmq
      
  redis:
    image: redis:alpine
    restart: always
    expose:
      - 6379

networks:
  default:
    external:
      name: app-network
